<?php namespace App\Models;

/**
 * Eloquent class to describe the complexes_analyses table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property int $id
 * @property int $complex_id
 * @property int $analyse_id
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ComplexesAnalyse whereAnalyseId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ComplexesAnalyse whereComplexId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ComplexesAnalyse whereId($value)
 * @mixin \Eloquent
 */
class ComplexesAnalyse extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'complexes_analyses';

    public $timestamps = false;

    protected $fillable = ['complex_id', 'analyse_id'];


}
